<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <StartupObject>CustomClipboardManager.Program</StartupObject>
    <!-- Size reduction -->
    <ApplicationIcon>Clipboard.ico</ApplicationIcon>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Clipboard.ico" />
    <Resource Include="Clipboard.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\*.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="WebSetup\**" />
    <Page Remove="WebSetup\**" />
    <Resource Remove="WebSetup\**" />
    <EmbeddedResource Remove="WebSetup\**" />
    <None Remove="WebSetup\**" />
    <Compile Remove="scratch\**" />
    <Page Remove="scratch\**" />
    <Resource Remove="scratch\**" />
    <EmbeddedResource Remove="scratch\**" />
    <None Remove="scratch\**" />
    <Compile Remove="Tests\**" />
    <Page Remove="Tests\**" />
    <Resource Remove="Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
    <None Remove="Tests\**" />
  </ItemGroup>

</Project>
